tasks:
- ssh-keys: null
- install.ship_utilities:
- rhceph_ansible: null
- nfs_ganesha_rgw_v2:
    test-name: test_on_s3_io_move
    nfs-version: 4
    mount-dir: ganesha-mount
    config:
        bucket_count: 4
        objects_count: 2000
        objects_size_range:
            min: 5
            max: 10
            io_op_config:
                create: true
