config:
 user_count: 1
 bucket_count: 1
 objects_count: 58900
 objects_size_range:
  min: 10
  max: 10
 local_file_delete: true 
 test_ops:
      create_bucket: true
      create_object: true
      object_structure: flat
      radosgw_listing_ordered : true
      radoslist: false
      delete_bucket_object: true
